### ISSUE TITLE
Adding formatting of JSON files in CI

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/deeployer#11]
Just like with Jsonnet files, we should make sure all JSON files are correctly linted.

**Comment by mika1K** [comment]
I think we can use the python module `json.tool` [Json-commandLine](https://docs.python.org/fr/3/library/json.html#json-commandline) to prevent linting from sorting keys. It have the _**--sort-keys**_ option, whose default is False. 
![Capture d’écran du 2020-04-10 17-22-39](https://user-images.githubusercontent.com/47780109/79002094-03d34900-7b50-11ea-8d45-7d9a2efdee9a.png)

**Comment by mika1K** [comment]
We can us it according to this demo 
![Capture d’écran du 2020-04-10 17-30-38](https://user-images.githubusercontent.com/47780109/79002613-1e59f200-7b51-11ea-9c7f-4ea6fcd35700.png)

**Comment by moufmouf** [comment]
:+1:

Did you see you could do the same thing with `jq . file.json` ?
(in case python is not installed in the Docker image, we know jq is already there!)

**Comment by mika1K** [comment]
I tried with jq but problem is that when using it with multiple files like this `jq . files*.json` it outputs the linted content of matched files one after another on stdout. Which cause a problem to redirect appropriately content cause this is not working  : `jq . files*.json > files*.json` . It can be cool if you had an idea about redirection here, meanwhile Im looking more !

**Comment by mika1K** [comment]
Finally this worked : https://github.com/zaach/jsonlint
