### ISSUE TITLE
Add a JSONSchema file

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/deeployer#3]
Define a JSONSchema file for deeployer.json (note: change deeployer.libsonnet to deeployer.json)

Add the schema definition at the beginning of the  deeployer.json file.

See: https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json

**Comment by mika1K** [comment]
closes #3

**Comment by mika1K** [comment]
Added deeeployer.schema.json
